version: '3.8'

services:
  angular-app:
    build:
      context: ./proyecto-angular
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./proyecto-angular:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ng serve --host 0.0.0.0 --poll 2000
    networks:
      - app-network

  fastapi-app:
    build:
      context: ./proyecto-fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./proyecto-fastapi:/app
    env_file:
      - ./proyecto-fastapi/.env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    name: app-network